# Generated by Django 2.2 on 2020-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_product_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
