# Generated by Django 2.2 on 2020-07-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='product',
            new_name='products',
        ),
    ]
